[package]
name = "zcsi-pkt"
version = "0.1.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>"]
edition = "2024"
rust-version = "1.91.1"

[dependencies]
e2d2 = { path = "../../framework", features = ["performance"] }
time = ">=0.1.0"
getopts = "*"
rand = "0.3"
fnv = "*"
macaddr = { version = ">=1.0", features = ["serde"] }
uuid = { version = ">=0.7", features = ["v4"] }

[features]
default = []
print = []
