[package]
name = "e2d2"
version = "1.0.11"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>", "Rainer Stademann <rainer.stademann@silverengine.de>"]
build = "build.rs"
edition = "2024"
rust-version = "1.91.1"

[lib]
doctest = false

[dependencies]
libc = ">= 0.2.79"
log = ">=0.3"
getopts = "*"
byteorder = "*"
fnv = "*"
twox-hash = "*"
regex = "*"
lazy_static = "*"
net2 = "*"
# NIX restricts us to just unix for now, we can fix this if someone cares at a later point.
nix = { version = ">=0.30.1", features =["event"] }
toml = ">=0.6"
# Hack for SHM
uuid= { version = ">=0.7", features=["v4"] }
macaddr = { version = ">=1.0", features = ["serde"] }
separator =  ">= 0.3"
serde_derive = ">=1.0"
serde = ">=1.0"
ipnet = ">=1.0"

[features]
default = []
performance = []
packet_offset = []
dev = []
sctp = []

